const actionTypes = {
    REGISTER: 'REGISTER',
    LOGOUT: 'LOGOUT',
    LOGIN: 'LOGIN',

    GET_POSTS: "GET_POSTS",
    GET_POSTS_LIMIT: "GET_POSTS_LIMIT",
    GET_POSTS_ADMIN: 'GET_POSTS_ADMIN',
    GET_NEW_POST: "GET_NEW_POST",
    EDIT_DATA: 'EDIT_DATA',
    RESET_DATAEDIT: 'RESET_DATAEDIT',
    GET_OUTSTANDING: 'GET_OUTSTANDING',

    GET_CATEGORIES: 'GET_CATEGORIES',
    GET_PRICES: 'GET_PRICES',
    GET_AREAS: 'GET_AREAS',
    GET_PROVINCES: 'GET_PROVINCES',
    GET_FOODTYPES: 'GET_FOODTYPES',

    // USER
    GET_CURRENT: 'GET_CURRENT',
    IS_ADMIN: 'IS_ADMIN',
    LOADING: 'LOADING',
    MODAL: 'MODAL',

}

export default actionTypes